# 100개 뉴스기사 수집 (제목, 그 링크 안에 있는 전체 본문내용)

In [58]:
# !pip install undetected-chromedriver
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

driver = uc.Chrome()
driver.get("https://search.naver.com/search.naver?ssc=tab.news.all&where=news&sm=tab_jum&query=%EB%8C%80%EA%B5%AC%EC%9D%80%ED%96%89")

In [65]:
total = []

while True:
    news = driver.find_element(By.CSS_SELECTOR, "ul.list_news._infinite_list").find_elements(By.CSS_SELECTOR, "li.bx")
    for i in news:
        links = (i.find_elements(By.CSS_SELECTOR, "a.info"))
        if len(links) == 2:      # 원본기사링크랑 네이버기사링크 둘다 있는 경우
            title = (i.find_element(By.CSS_SELECTOR, 'a.news_tit').get_attribute("title"))
            link = links[-1].get_attribute("href")           # 두 링크 중 마지막 거 (= 네이버기사 링크)
            A = [title, link]       # 제목과 링크만 모은다
            if A not in total:
                total.append(A)
    body = driver.find_element(By.CSS_SELECTOR, "body")
    body.send_keys(Keys.PAGE_DOWN)
    time.sleep(2)
    print(f"{len(total)}개 뉴스기사 수집완료")
    if len(total) >= 100:
        break

57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
57개 뉴스기사 수집완료
60개 뉴스기사 수집완료
60개 뉴스기사 수집완료
60개 뉴스기사 수집완료
60개 뉴스기사 수집완료
63개 뉴스기사 수집완료
63개 뉴스기사 수집완료
63개 뉴스기사 수집완료
63개 뉴스기사 수집완료
63개 뉴스기사 수집완료
67개 뉴스기사 수집완료
67개 뉴스기사 수집완료
67개 뉴스기사 수집완료
67개 뉴스기사 수집완료
67개 뉴스기사 수집완료
67개 뉴스기사 수집완료
70개 뉴스기사 수집완료
70개 뉴스기사 수집완료
70개 뉴스기사 수집완료
70개 뉴스기사 수집완료
73개 뉴스기사 수집완료
73개 뉴스기사 수집완료
73개 뉴스기사 수집완료
73개 뉴스기사 수집완료
78개 뉴스기사 수집완료
78개 뉴스기사 수집완료
78개 뉴스기사 수집완료
78개 뉴스기사 수집완료
83개 뉴스기사 수집완료
83개 뉴스기사 수집완료
83개 뉴스기사 수집완료
83개 뉴스기사 수집완료
83개 뉴스기사 수집완료
84개 뉴스기사 수집완료
84개 뉴스기사 수집완료
84개 뉴스기사 수집완료
84개 뉴스기사 수집완료
84개 뉴스기사 수집완료
88개 뉴스기사 수집완료
88개 뉴스기사 수집완료
88개 뉴스기사 수집완료
88개 뉴스기사 수집완료
91개 뉴스기사 수집완료
91개 뉴스기사 수집완료
91개 뉴스기사 수집완료
91개 뉴스기사 수집완료
91개 뉴스기사 수집완료
92개 뉴스기사 수집완료
92개 뉴스기사 수집완료
92개 뉴스기사 수집완료
92개 뉴스기사 수집완료
92개 뉴스기사 수집완료
95개 뉴스기사 수집완료
95개 뉴스기사 수집완료
95개 뉴스기사 수집완료
95개 뉴스기사 수집완료
97개 뉴스기사 수집완료
97개 뉴스기사 수집완료
97개 뉴스기사 수집완료
97개 뉴스기사 수집완료
98개 뉴스기사 수집완료
98개 뉴스기사 수집완료
98개 뉴스기사 수집완료
98개 뉴스기사 수집완료
99개 뉴스기사 수집완료
99개 뉴스기사 수집완료
99개 뉴스기사 수집완료
99개 뉴스기사 수집완료
100개 뉴스기사 수집완료

In [69]:
import pandas as pd
df = pd.DataFrame(total, columns = ["제목", "링크"])
df

,제목,링크
0,"'정체성 무엇?' 시중은행 iM뱅크, 가계대출 규제는 대구은행처럼",https://n.news.naver.com/mnews/article/648/000...
1,대구 은행서 4천만원 턴 30대 은행강도 1시간여 만 검거,https://n.news.naver.com/mnews/article/422/000...
2,[속보] 김태오 전 대구은행 DGB금융그룹 회장 원심 파기 징역 2년에 집유 3년,https://n.news.naver.com/mnews/article/657/000...
3,"독립운동 성지 칠곡, 삼일절 헌화로 역사와 미래 잇는다",https://n.news.naver.com/mnews/article/003/001...
4,"""돈 안 굴려도 이자 쏠쏠했는데""…은행 갔다가 '화들짝'",https://n.news.naver.com/mnews/article/015/000...
...,...,...
95,"대구은행 ""시중은행 전환 의결 환영…국가경제 변화 이끌겠다""",https://n.news.naver.com/mnews/article/001/001...
96,"시중은행 전환 대구은행, 'iM뱅크'로 새 출발",https://n.news.naver.com/mnews/article/052/000...
97,"대구은행, 설립 57년 만에 시중은행으로 재탄생",https://n.news.naver.com/mnews/article/031/000...
98,"대구은행, '전국구' 도약 앞두고 건전성 악화",https://n.news.naver.com/mnews/article/008/000...
99,‘내부통제 부실’ 우려 안은 채…대구은행 ‘전국행’ 일단 출발,https://n.news.naver.com/mnews/article/032/000...

In [73]:
box = []
for i in df["링크"]:
    driver.implicitly_wait(10)
    driver.get(i)
    try:
        content = driver.find_element(By.CSS_SELECTOR, "div.newsct_article._article_body")
    except:
        content = driver.find_element(By.CSS_SELECTOR, "div._article_content")    # 스포츠 뉴스 기사의 경우
    box.append(content.text)

In [74]:
df["내용"] = box
df.to_excel("대구은행.xlsx", index = False)
df

,제목,링크,내용
0,"'정체성 무엇?' 시중은행 iM뱅크, 가계대출 규제는 대구은행처럼",https://n.news.naver.com/mnews/article/648/000...,시중은행 가계대출 증가율 1~2% 대상 미포함\n지방 대출 압도적…지방은행 준하는 ...
1,대구 은행서 4천만원 턴 30대 은행강도 1시간여 만 검거,https://n.news.naver.com/mnews/article/422/000...,대구중부경찰서 [연합뉴스 자료]\n\n대구 중부경찰서는 오늘(26일) 은행에서 직원...
2,[속보] 김태오 전 대구은행 DGB금융그룹 회장 원심 파기 징역 2년에 집유 3년,https://n.news.naver.com/mnews/article/657/000...,캄보디아 공무원에게 뇌물을 준 혐의 등으로 기소된 김태오 전 DGB금융그룹 지주 회...
3,"독립운동 성지 칠곡, 삼일절 헌화로 역사와 미래 잇는다",https://n.news.naver.com/mnews/article/003/001...,"독립운동가 후손 부축, 헌화한 김재욱 군수\n[칠곡=뉴시스] 장진홍 의사의 손자 장..."
4,"""돈 안 굴려도 이자 쏠쏠했는데""…은행 갔다가 '화들짝'",https://n.news.naver.com/mnews/article/015/000...,은행 예·적금 금리 年 1%대 등장\n예테크족 속 탄다\n\n기준금리 인하에 수직 ...
...,...,...,...
95,"대구은행 ""시중은행 전환 의결 환영…국가경제 변화 이끌겠다""",https://n.news.naver.com/mnews/article/001/001...,"내부통제 혁신위원회 신설…""금융사고 방지""\n\n\nDGB 대구은행\n[DGB 대구..."
96,"시중은행 전환 대구은행, 'iM뱅크'로 새 출발",https://n.news.naver.com/mnews/article/052/000...,시중은행으로 전환한 대구은행이 사명을 'iM뱅크'로 바꾸고 새롭게 출발합니다.\n\...
97,"대구은행, 설립 57년 만에 시중은행으로 재탄생",https://n.news.naver.com/mnews/article/031/000...,1992년 평화은행 이후 일곱 번째 시중은행\n대구은행이 57년 만에 지방은행 간판...
98,"대구은행, '전국구' 도약 앞두고 건전성 악화",https://n.news.naver.com/mnews/article/008/000...,"대구은행, 주택담보대출 잔액/그래픽=윤선정\n시중은행 전환심사를 앞둔 DGB대구은행..."
99,‘내부통제 부실’ 우려 안은 채…대구은행 ‘전국행’ 일단 출발,https://n.news.naver.com/mnews/article/032/000...,"32년 만에 새 ‘시중은행’ 출범…금융위, 전환 인가\n\n\n윤 대통령 ‘과점’ ..."