# Bag of Words (BoW) : 단어 가방
각 단어별로 몇번 나왔는지를 중요하게 생각

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'He is a great great person.',
    'She is a great person.',
    'Python is a great programming language.',
    'Is Python a great great language?'
]

cv = CountVectorizer()
matrix = cv.fit_transform(corpus)
matrix

# 4개의 문장이 있었는데 단어가방을 만드니까 4행 8열짜리로 나왔다

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [12]:
cv.vocabulary_      # 단어들에 대해 컴퓨터가 라벨링

{'he': 1,
 'is': 2,
 'great': 0,
 'person': 4,
 'she': 7,
 'python': 6,
 'programming': 5,
 'language': 3}

In [13]:
import pandas as pd

pd.DataFrame(matrix.toarray(), columns = cv.get_feature_names_out())

   great  he  is  language  person  programming  python  she
0      2   1   1         0       1            0       0    0
1      1   0   1         0       1            0       0    1
2      1   0   1         1       0            1       1    0
3      2   0   1         1       0            0       1    0

## 예제

In [20]:
df = pd.read_excel("Data/text data.xlsx").dropna()

cv = CountVectorizer()
matrix = cv.fit_transform(df["document"])
matrix

<37533x101224 sparse matrix of type '<class 'numpy.int64'>'
	with 268004 stored elements in Compressed Sparse Row format>

In [19]:
pd.DataFrame(matrix.toarray(), columns = cv.get_feature_names_out())

,00,00000,0000000000,00001점,000원으로,000키로미터,007,007도,007로저무어주연,007사상,...,힙합에,힙합은,힙합을,힙합하는,힛걸,힛걸에,힛걸을,힛걸의,힝군대갈때이후로,流水
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37528,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37529,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37530,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37531,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37532,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
from konlpy.tag import Okt

df = pd.read_excel("Data/text data.xlsx").dropna()

okt = Okt()

def tokenizer(x):
    return okt.morphs(x)

cv = CountVectorizer(tokenizer=tokenizer)

X = cv.fit_transform(df["document"])
X

C:\Users\campus4D019\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

<37533x47758 sparse matrix of type '<class 'numpy.int64'>'
	with 496276 stored elements in Compressed Sparse Row format>