## PER(Price-Earnings Ratio, 주가수익비율)
```PER(주가수익비율)```이란 현재 주가가 그 회사의 1주당 순이익(EPS)의 몇 배인지를 나타내는 투자 지표입니다. 쉽게 말해, 투자자들이 그 회사의 이익 1원에 대해 얼마를 지불할 의사가 있는지를 보여주는 값이죠.

```
EPS = 당기순이익(기업이 특정 회계 기간 동안 모든 수익에서 모든 비용과 세금을 차감한 후 남은 최종적인 이익) / 총 발행 주식 수
PER = 현재 주가 / 주당순이익(EPS)
```

PER을 이해하는 가장 직관적인 방법은 '투자 원금 회수 기간'으로 생각하는 것입니다. 예를 들어, 어떤 회사의 PER이 10이라면, 그 회사가 현재와 같은 순이익을 계속 낸다고 가정했을 때 투자 원금을 모두 회수하는 데 10년이 걸린다는 의미로 해석할 수 있습니다.

따라서 PER은 특정 주식이 현재 시장에서 고평가되었는지, 아니면 저평가되었는지를 판단하는 중요한 잣대로 활용됩니다.

* 높은 PER (고PER): 투자자들이 미래 성장 가능성을 높게 평가하여 현재 이익 수준에 비해 높은 가격을 지불하고 있음을 의미합니다. 성장주에서 흔히 나타납니다.
* 낮은 PER (저PER): 현재 주가가 이익 수준에 비해 낮게 형성되어 있음을 의미합니다. 저평가된 가치주일 수도 있지만, 성장성이 둔화되었거나 시장에서 소외된 주식일 수도 있습니다.
* 음수 PER: PER이 음수라는 것은 해당 기업이 돈을 버는 것이 아니라, 오히려 손실(적자)을 보고 있다는 의미입니다.

In [36]:
import pandas as pd
df = pd.read_excel("Data/2025-06-30_국내주식.xlsx")
df.head()

,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,고가,...,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율,소속
0,삼성전자,60350,하락 450,-0.74%,100,6100767,369197,17340470,61200,61200,...,1446.0,16.20,398.34,49.74,11.69,9.03,7.10,1.02,41772.8,KOSPI
1,SK하이닉스,292250,"상승 8,250",+2.90%,5000,1634615,472433,5134863,288500,294500,...,2204.0,102.02,403.58,55.52,8.19,31.06,17.98,2.48,1911.2,KOSPI
2,삼성바이오로직스,996000,보합0,0.00%,2500,10043,10008,38057,1001000,1001000,...,0.0,23.08,18.53,12.89,55.40,10.45,6.49,6.28,6041.4,KOSPI
3,LG에너지솔루션,295500,"상승 7,500",+2.60%,500,96779,28532,219699,290000,297500,...,NaN,-24.08,-73.40,4.09,-59.41,-4.93,0.64,3.27,15864.8,KOSPI
4,두산에너빌리티,67600,"상승 1,800",+2.74%,5000,7725046,539550,7601019,70400,72200,...,NaN,-7.71,-30.65,24.43,-425.16,1.52,1.55,5.69,90.8,KOSPI

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4129 entries, 0 to 4128
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   종목명      4129 non-null   object
 1   현재가      4129 non-null   int64
 2   전일비      4129 non-null   object
 3   등락률      4129 non-null   object
 4   액면가      4129 non-null   int64
 5   거래량      4129 non-null   int64
 6   거래대금     4129 non-null   int64
 7   전일거래량    4129 non-null   int64
 8   시가       4129 non-null   int64
 9   고가       4129 non-null   int64
 10  저가       4129 non-null   int64
 11  매수호가     4129 non-null   int64
 12  매도호가     4129 non-null   int64
 13  매수총잔량    4129 non-null   int64
 14  매도총잔량    4129 non-null   int64
 15  상장주식수    4129 non-null   int64
 16  시가총액     4129 non-null   int64
 17  매출액      2554 non-null   float64
 18  자산총계     2637 non-null   float64
 19  부채총계     2637 non-null   float64
 20  영업이익     2637 non-null   float64
 21  당기순이익    2637 non-null   float64
 22  주당순이익    2749 non-null   float64
 23  보통주배당금   1663 non-null   float64
 24  매출액증가율   2486 non-null   float64
 25  영업이익증가율  2544 non-null   float64
 26  외국인비율    4129 non-null   float64
 27  PER      2747 non-null   float64
 28  ROE      2544 non-null   float64
 29  ROA      2544 non-null   float64
 30  PBR      2749 non-null   float64
 31  유보율      2637 non-null   float64
 32  소속       4129 non-null   object
dtypes: float64(15), int64(14), object(4)
memory usage: 1.0+ MB

In [4]:
df2 = df[['종목명', 'PER']].dropna().sort_values("PER")
df2

           종목명      PER
2359      네이처셀 -9416.67
1357   한화투자증권우 -2910.00
51       카카오페이 -2470.97
2482     바이오다인 -2304.29
207     한화투자증권 -2213.33
...        ...      ...
2734      에브리봇  2118.75
2390      오스코텍  2890.00
923     한국수출포장  3025.00
3349     그린플러스  3440.00
2337  레인보우로보틱스  6841.46

[2747 rows x 2 columns]

## ROE(Return on Equity, 자기자본이익률)
```ROE(Return on Equity, 자기자본이익률)```란 주주의 돈(자기자본)을 가지고 회사가 1년 동안 얼마나 효율적으로 이익을 냈는지를 나타내는 핵심 수익성 지표입니다.

```ROE: 당기순이익 / 평균자기자본 * 100```

쉽게 말해, "내가 투자한 돈으로 회사가 얼마나 잘 장사해서 돈을 벌었나?"를 보여주는 성적표라고 할 수 있습니다.

직관적인 예시:
ROE가 20%라면, 주주가 1억 원을 투자한 회사에서 1년에 2,000만 원의 순이익을 만들어냈다는 의미입니다. 만약 ROE가 5%인 회사보다 4배 더 효율적으로 주주의 돈을 굴린 셈이죠.

투자의 현인 워런 버핏은 "우리가 찾는 기업은 지난 10년간 ROE가 꾸준히 15% 이상이었던 기업이다"라고 말할 정도로, 장기적으로 꾸준히 높은 ROE를 기록하는 기업을 '좋은 기업'의 가장 중요한 조건으로 꼽았습니다. 높은 ROE는 그 기업이 강력한 경쟁력(경제적 해자)을 가지고 있다는 강력한 증거이기 때문입니다.

In [5]:
df2 = df[['종목명', 'ROE']].dropna()
df2.sort_values("ROE", ascending = False)

         종목명       ROE
837     효성화학  10663.68
3377      E8   2823.10
1540      한창    946.65
2786    현대사료    340.50
3921   선샤인푸드    286.29
...      ...       ...
3552    푸드나무   -364.32
3965   세종메디칼   -375.00
2721   푸른소나무   -417.81
3291  제일엠앤에스   -791.40
3234    심플랫폼  -1583.24

[2544 rows x 2 columns]

## PBR(Price-to-Book Ratio, 주가순자산비율)
```PBR(Price-to-Book Ratio, 주가순자산비율)```이란 회사의 현재 주가가 회사의 순자산(청산가치)에 비해 몇 배로 거래되고 있는지를 나타내는 가치 평가 지표입니다.

여기서 '순자산(자기자본)'이란, 회사의 모든 자산을 다 팔고 모든 빚을 갚고 나서 주주들에게 남는 순수한 몫을 의미합니다. 즉, 회사의 '청산가치'라고 볼 수 있습니다.

직관적인 예시:
어떤 회사의 PBR이 0.7이라면, 현재 시장에서 이 회사의 주식을 모두 사들이는 데 드는 비용(시가총액)이, 이 회사를 당장 청산해서 주주들에게 나눠줄 수 있는 돈(순자산)보다 30%나 저렴하다는 의미입니다.

가치 투자의 창시자 벤저민 그레이엄은 이 PBR을 '안전마진'의 개념으로 활용했습니다. 그는 주가가 회사의 순자산 가치보다도 낮게 거래될 때(즉, PBR < 1) 투자하면, 설령 그 회사가 망하더라도 투자 원금의 상당 부분을 회수할 수 있다고 보았습니다.

In [6]:
df2 = df[['종목명', 'PBR']].dropna()
df2[(df2['PBR'] < 1) & (df2['PBR'] > 0)].sort_values("PBR")

            종목명   PBR
4014      씨엑스아이  0.04
3724   오가닉티코스메틱  0.09
3956        로스웰  0.09
3755       헝셩그룹  0.09
3825  이스트아시아홀딩스  0.10
...         ...   ...
3946       셀레믹스  0.99
3928   KB제27호스팩  0.99
3226      오픈베이스  0.99
3001        위드텍  0.99
2847    이노와이어리스  0.99

[1364 rows x 2 columns]

### 전략1: 고ROE & 저PBR 조합 전략 (가성비 좋은 우량주 찾기)
* 고ROE (High ROE): 수익성이 좋은 '우량 기업'을 고르는 기준입니다. (예: ROE > 15% 또는 시장 평균 이상)
* 저PBR (Low PBR): 하지만 아무리 좋은 기업도 비싸게 사면 의미가 없습니다. PBR(주가순자산비율)을 통해 기업의 순자산 가치 대비 주가가 '저렴한' 기업을 고릅니다. (예: PBR < 1.5 또는 업종 평균 이하)

In [7]:
df2 = df[["종목명", 'ROE', 'PBR']].dropna()
df2[(df2['ROE'] > 15) & (df2['PBR'] < 1.5)]

         종목명     ROE   PBR
10        기아   19.09  0.69
21     SK스퀘어   21.70  1.20
23       HMM   15.35  0.72
62    DB손해보험   18.98  0.91
85      키움증권   15.98  1.08
...      ...     ...   ...
3742    싸이버원   27.36  1.00
3761   원바이오젠   16.39  1.01
3870   기산텔레콤   16.39  0.66
3921   선샤인푸드  286.29 -3.98
3946    셀레믹스   56.97  0.99

[134 rows x 3 columns]

### 전략 2: 전통적 저PBR 전략 (벤저민 그레이엄 방식)
PBR < 1, 더 엄격하게는 PBR < 0.7 인 기업들을 매수하는 전략입니다. 주식을 사업의 일부로 보고, 그 사업의 본질적인 자산 가치보다도 싸게 사는 것을 목표로 합니다. 극단적인 저평가 상태에 있는 주식을 찾아 '안전마진'을 확보하는 고전적인 가치 투자 전략입니다. 이 전략의 가장 큰 약점은 ```'가치 함정(Value Trap)'```에 빠질 수 있다는 것입니다. PBR이 낮은 데에는 그럴만한 이유(예: 수익성 악화, 사양 산업, 부실한 자산)가 있을 수 있습니다. 단순히 싸다는 이유만으로 매수했다가 주가가 영원히 오르지 않을 수 있습니다.

In [8]:
df2 = df[['종목명', 'PBR']].dropna()
df2[(df2['PBR'] < 0.7) & (df2['PBR'] > 0)].sort_values("PBR")

            종목명   PBR
4014      씨엑스아이  0.04
3956        로스웰  0.09
3755       헝셩그룹  0.09
3724   오가닉티코스메틱  0.09
3825  이스트아시아홀딩스  0.10
...         ...   ...
3454      에이치시티  0.69
106      JB금융지주  0.69
1153   미래에셋맵스리츠  0.69
3799       소프트센  0.69
533   제이에스코퍼레이션  0.69

[971 rows x 2 columns]

## 연습문제
1. '가치주'의 특징 중 하나인 '고배당'과 '안정성'을 찾아봅시다. ROE가 8%를 초과하면서 PBR은 1 미만인 종목들을 찾아, ROE가 높은 순서대로 상위 10개 종목의 종목명, ROE, PBR을 출력하는 코드를 작성하세요. (단, PBR은 0보다 커야 합니다.)

In [14]:
df2 = df[["종목명", "ROE", "PBR"]].dropna()
df2[(df2["ROE"] > 0.8) & (df2["PBR"] < 1) & (df2["PBR"] > 0)].sort_values("ROE", ascending=False)

        종목명       ROE   PBR
837    효성화학  10663.68  0.49
1779   일정실업     74.89  0.83
1095  일동홀딩스     72.94  0.60
2996     광무     60.03  0.63
3946   셀레믹스     56.97  0.99
...     ...       ...   ...
3331   티플랙스      0.86  0.48
541    사조산업      0.86  0.57
1583     진도      0.85  0.22
1449   대한방직      0.85  0.17
957    진흥기업      0.81  0.42

[868 rows x 3 columns]

2. '가치 함정(Value Trap)'일 가능성이 있는 기업의 특징은 PBR은 매우 낮지만, 수익성(ROE) 역시 매우 낮은 것입니다. PBR이 0.5 미만이지만 ROE는 5% 미만인 기업들을 찾아 종목명, PBR, ROE를 출력하는 코드를 작성하세요. (단, PBR과 ROE 모두 음수는 제외합니다.)

In [40]:
df2 = df[["종목명", "PBR", "ROE"]].dropna()
df2 = df2[(df2["PBR"] >= 0) & (df2["ROE"] >= 0)]
df2[(df2["PBR"] < 0.5) & (df2["ROE"] < 5)]

           종목명   PBR   ROE
25    POSCO홀딩스  0.36  2.00
43          LG  0.45  2.16
100         GS  0.32  4.12
166     iM금융지주  0.34  3.60
167      DL이앤씨  0.45  4.77
...        ...   ...   ...
3929     패션플랫폼  0.33  1.75
3950        삼일  0.36  1.96
3972    글로벌에스엠  0.19  0.49
3981      에프알텍  0.36  1.90
3992    티피씨글로벌  0.31  2.38

[188 rows x 3 columns]

3. 데이터프레임에 있는 부채총계와 자산총계를 사용하여 부채비율을 계산해 봅시다. ```부채비율(%)``` 이라는 새로운 컬럼을 만드세요.
    * 이 컬럼의 값은 (부채총계 / (자산총계 - 부채총계)) * 100 공식으로 계산하여 저장하세요. (자기자본 = 자산총계 - 부채총계)
    * 계산된 부채비율(%)이 100% 미만으로 재무적으로 안정적인 기업들 중, PBR이 가장 낮은 5개 기업의 종목명, PBR, 부채비율(%)을 출력하세요.

In [19]:
df["부채비율(%)"] = df["부채총계"] / (df["자산총계"] - df["부채총계"]) * 100
df2 = df[["종목명", "PBR", "부채비율(%)"]].dropna()
df2[df2["부채비율(%)"] < 100].sort_values("PBR").head(5)

           종목명   PBR     부채비율(%)
2818     엔케이맥스 -7.32 -200.000000
2956       시스웍 -6.78 -231.578947
3803  디에이테크놀로지 -4.10 -935.714286
3921     선샤인푸드 -3.98 -584.745763
1540        한창 -2.84 -547.133758

4. 소속 컬럼을 활용하여 KOSPI와 KOSDAQ 시장의 평균 PER, PBR을 각각 계산하고 비교하는 코드를 작성하세요.

In [23]:
kospi = df[df["소속"] == "KOSPI"]
kosdaq = df[df["소속"] == "KOSDAQ"]

print(kospi["PER"].mean(), kospi["PBR"].mean())
print(kosdaq["PER"].mean(), kosdaq["PBR"].mean())

5.62527139874739 1.280866388308977
5.613834544438235 2.406175321049693

5. 조엘 그린블라트의 '마법 공식'을 간소화하여 구현해 봅시다.
    * 수익성 순위: ROE가 높은 순서대로 순위를 매겨 ROE_Rank 컬럼에 저장하세요.
    * 저평가 순위: PBR이 낮은 순서대로 순위를 매겨 PBR_Rank 컬럼에 저장하세요. (단, PBR > 0)
    * 두 순위를 더한 Total_Rank 컬럼을 만들고, 이 종합 순위가 가장 낮은(가장 좋은) 상위 10개 기업의 종목명, ROE, PBR, Total_Rank를 출력하세요.

In [31]:
df2 = df[["종목명", "ROE", "PBR"]].dropna()
df2 = df2[df2["PBR"] > 0]

df2["ROE_Rank"] = df2["ROE"].rank(ascending=False)
df2["PBR_Rank"] = df2["PBR"].rank(ascending=True)
df2["Total_Rank"] = df2["ROE_Rank"] + df2["PBR_Rank"]
df2[["종목명", "ROE", "PBR", "Total_Rank"]].sort_values("Total_Rank").head(10)

          종목명    ROE   PBR  Total_Rank
3558   오션인더블유  32.03  0.19        77.0
1725  KC그린홀딩스  23.91  0.12       115.0
652        서연  18.34  0.26       292.0
1273    티에이치엔  24.54  0.35       345.0
1126     삼정펄프  15.76  0.28       385.0
3087   유성티엔에스  12.70  0.20       411.0
2526     서희건설  17.64  0.33       419.5
1195   화승알앤에이  24.66  0.40       431.5
3728      에코캡  20.43  0.38       436.0
534      서연이화  14.87  0.29       439.0

6. 너무 작은 규모의 기업을 제외하기 위해 '시가총액' 필터를 추가해 봅시다. '시가총액'이 1조 원 이상인 기업들 중에서, ```ROE > 8%, 0 < PBR < 1```을 만족하는 기업들을 찾아 종목명, 시가총액, ROE, PBR을 출력하세요. 시가총액은 (억) 단위입니다.

In [41]:
df2 = df[["종목명", "시가총액", "ROE", "PBR"]].dropna()
df2 = df2[df2["시가총액"] >= 10000]

df2[(df2["ROE"] > 8) & (df2["PBR"] > 0) & (df2["PBR"] < 1)]
df2[["종목명", "시가총액", "ROE", "PBR"]]

           종목명     시가총액    ROE   PBR
0         삼성전자  3572501   9.03  1.02
1       SK하이닉스  2127587  31.06  2.48
2     삼성바이오로직스   708893  10.45  6.28
3     LG에너지솔루션   691470  -4.93  3.27
4      두산에너빌리티   433019   1.52  5.69
...        ...      ...    ...   ...
2389    대주전자재료    11084  19.30  4.62
2390      오스코텍    11054   0.77  9.08
2391      하림지주    10596   0.90  0.30
2392      SOOP    10460  30.21  2.48
2394        원텍    10193  25.76  7.54

[280 rows x 4 columns]